esphome:
  name: spray
  friendly_name: spray

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "SomePassword"

ota:
  - platform: esphome
    password: "SomePassword"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Spray Fallback Hotspot"
    password: "SomePassword"

captive_portal:

web_server:
  port: 80

switch:
  - platform: gpio
    pin: GPIO13
    id: relay
    name: "Relay"
    inverted: True
    icon: "mdi:power"

button:
  - platform: template
    name: "Spray"
    icon: "mdi:timer"
    on_press:
      - switch.turn_on: relay
      - delay: 20s
      - switch.turn_off: relay
